### ISSUE TITLE
A ‘how to build locally’ section in README would be better.

### ISSUE THREAD

**Issue by whystar** [ccf-countdown/ccf-countdown.github.io#1]
After I add a conference, I want to preview the updated layout locally before pushing back the changes.  However I’m not familiar with the building process of this project. A ‘how to build locally’ section in README would be better.

**Comment by gitferry** [comment]
Thanks for your suggestion, it would be great to have an instruction on how to build the website locally, but I'm not familiar with this. It seems that you are a very experienced developer. Could you please submit a PR on this?

**Comment by gitferry** [comment]
Done.

**Comment by whystar** [comment]
👍 amazing, I will try to add some first-class conferences in the domain of software engineering.
